In [14]:
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
D = np.random.rand(10,5)
pca=PCA()
pca.fit(D) #训练数据
D

array([[0.56563412, 0.3105069 , 0.90637948, 0.93755073, 0.42909966],
       [0.81603346, 0.87679996, 0.47843088, 0.24484161, 0.27508207],
       [0.10467921, 0.70787414, 0.94653586, 0.20278051, 0.88299868],
       [0.64105759, 0.39468005, 0.73792687, 0.37480155, 0.94346019],
       [0.53724569, 0.69686996, 0.47656424, 0.13826672, 0.36273019],
       [0.40421263, 0.83884977, 0.47683633, 0.68772832, 0.34476464],
       [0.89849608, 0.1961186 , 0.51474411, 0.55647846, 0.84666884],
       [0.02483119, 0.74709665, 0.23943206, 0.99643747, 0.02343144],
       [0.07449104, 0.3478642 , 0.81647571, 0.32083018, 0.01825412],
       [0.52707664, 0.68121101, 0.79342374, 0.05572985, 0.90960466]])

In [15]:
pca.components_  #返回模型的特征向量

array([[-0.38309051,  0.14204901, -0.26805137,  0.47365771, -0.73270771],
       [ 0.47218144, -0.48787983, -0.08437333,  0.71357546,  0.1506956 ],
       [ 0.65829503,  0.40340718, -0.57968623, -0.19088605, -0.17730392],
       [ 0.28089476, -0.56073993,  0.25121148, -0.41017446, -0.61263249],
       [ 0.34355805,  0.51442076,  0.72241696,  0.24855154, -0.18350752]])

In [13]:
pca.explained_variance_ratio_

array([0.61219461, 0.17418648, 0.12904243, 0.08457648])

In [ ]:
'''
10个样本 5个属性向量

特征向量即为5个属性的向量

非数学领域的矩阵向量

'''